name: Build Chrome Extension & Upload it to Latest Release (for chrome-extension experimental branch)

on:
  push:
    branches:
      - chrome-extension
    tags:
      - '**'
jobs:
  build_chrome_extension:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        sparse-checkout: chrome-extension
    # Zip the extension
    - name: Zip extension
      run: |
        mkdir build
        cd chrome-extension
        zip -r ../build/chrome-extension.zip *
      working-directory: ${{ github.workspace }}
      
    # Upload the extension to the artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: chrome-extension
        path: 'chrome-extension'
    
    # Upload the extension to the release
    - name: upload binaries to release
      uses: softprops/action-gh-release@v1
      if: ${{startsWith(github.ref, 'refs/tags/') }}
      with:
          files: 'build/chrome-extension.zip'
          token: ${{ secrets.PAT }}
    
    # Upload the extension to the chrome web store
    # https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.1
      env: # Map to environment variables so they are available to the if statement below
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      # Skip if credentials are not set
      if: ${{ env.CLIENT_ID && env.CLIENT_SECRET && env.REFRESH_TOKEN && env.REFRESH_TOKEN != ''}}
      with:
        file-path: 'build/chrome-extension.zip'
        # https://chrome.google.com/webstore/developer/dashboard Create a new extension and get the extension id.
        # Upload the extension manually once to get the extension id.
        extension-id: lgafiioacndmgagmenljhcjckemnkide # Change this if you want to upload to your own extension
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}